
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world
{ 
    /// <summary>
    /// 大世界显示关卡Tag
    /// </summary>
    public enum LevelTag
    {
        /// <summary>
        /// 普通
        /// </summary>
        Ordinary = 0,
        /// <summary>
        /// 冷冻
        /// </summary>
        Cool = 1,
        /// <summary>
        /// 缓震
        /// </summary>
        Fragile = 2,
        /// <summary>
        /// 保鲜
        /// </summary>
        Natural = 3,
        /// <summary>
        /// 保温
        /// </summary>
        Heat = 4,
    }

} 

