
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world
{ 
    /// <summary>
    /// 大世界显示关卡难度
    /// </summary>
    public enum LevelDifficulty
    {
        /// <summary>
        /// 简单
        /// </summary>
        Easy = 0,
        /// <summary>
        /// 普通
        /// </summary>
        Medium = 1,
        /// <summary>
        /// 困难
        /// </summary>
        Hard = 2,
    }

} 

