
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world
{
/// <summary>
/// 城镇每个难度下的关卡名字典
/// </summary>
public sealed partial class TownLevelDict : Luban.BeanBase
{
    public TownLevelDict(JSONNode _buf) 
    {
        { if(!_buf["easyLevelName"].IsString) { throw new SerializationException(); }  easyLevelName = _buf["easyLevelName"]; }
        { if(!_buf["mediumLevelName"].IsString) { throw new SerializationException(); }  mediumLevelName = _buf["mediumLevelName"]; }
        { if(!_buf["hardLevelName"].IsString) { throw new SerializationException(); }  hardLevelName = _buf["hardLevelName"]; }
    }

    public static TownLevelDict DeserializeTownLevelDict(JSONNode _buf)
    {
        return new world.TownLevelDict(_buf);
    }

    public readonly string easyLevelName;
    public readonly string mediumLevelName;
    public readonly string hardLevelName;
   
    public const int __ID__ = 1976045932;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "easyLevelName:" + easyLevelName + ","
        + "mediumLevelName:" + mediumLevelName + ","
        + "hardLevelName:" + hardLevelName + ","
        + "}";
    }
}

}

