
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class BackpackTemplate : Luban.BeanBase
{
    public BackpackTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["bp_name"].IsString) { throw new SerializationException(); }  bpName = _buf["bp_name"]; }
        { if(!_buf["shape"].IsNumber) { throw new SerializationException(); }  shape = (level.GridShape)_buf["shape"].AsInt; }
        { if(!_buf["bp_size"].IsObject) { throw new SerializationException(); }  bpSize = ExternalTypeUtil.NewVector2Int(vector2int.Deserializevector2int(_buf["bp_size"]));  }
        { if(!_buf["bp_value"].IsNumber) { throw new SerializationException(); }  bpValue = _buf["bp_value"]; }
        { if(!_buf["bp_price"].IsNumber) { throw new SerializationException(); }  bpPrice = _buf["bp_price"]; }
        { if(!_buf["bp_localization"].IsObject) { throw new SerializationException(); }  bpLocalization = global.LocalizedString.DeserializeLocalizedString(_buf["bp_localization"]);  }
    }

    public static BackpackTemplate DeserializeBackpackTemplate(JSONNode _buf)
    {
        return new level.BackpackTemplate(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 货箱名称
    /// </summary>
    public readonly string bpName;
    /// <summary>
    /// 货箱形状
    /// </summary>
    public readonly level.GridShape shape;
    /// <summary>
    /// 货箱纵宽比（x列y行）
    /// </summary>
    public readonly UnityEngine.Vector2Int bpSize;
    /// <summary>
    /// 货箱价值（卖出）
    /// </summary>
    public readonly int bpValue;
    /// <summary>
    /// 货箱售价（买入）
    /// </summary>
    public readonly int bpPrice;
    /// <summary>
    /// 本地化名称索引
    /// </summary>
    public readonly global.LocalizedString bpLocalization;
   
    public const int __ID__ = 962842980;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        bpLocalization?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "bpName:" + bpName + ","
        + "shape:" + shape + ","
        + "bpSize:" + bpSize + ","
        + "bpValue:" + bpValue + ","
        + "bpPrice:" + bpPrice + ","
        + "bpLocalization:" + bpLocalization + ","
        + "}";
    }
}

}

