
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level
{ 
    public enum BuildingType
    {
        /// <summary>
        /// 普通建筑
        /// </summary>
        Ordinary = 0,
        /// <summary>
        /// 肉店
        /// </summary>
        MeatShop = 1,
        /// <summary>
        /// 百货店
        /// </summary>
        Mall = 2,
        /// <summary>
        /// 木材商店
        /// </summary>
        WoodFactory = 3,
        /// <summary>
        /// 电子商店
        /// </summary>
        Electronic = 4,
        /// <summary>
        /// 牛奶工厂
        /// </summary>
        MilkFactory = 5,
        /// <summary>
        /// 起点
        /// </summary>
        Origin = 6,
        /// <summary>
        /// 升级点
        /// </summary>
        Upgrade = 7,
        /// <summary>
        /// 海鲜市场
        /// </summary>
        SeafoodMarket = 8,
        /// <summary>
        /// 礼品店
        /// </summary>
        GiftShop = 9,
        /// <summary>
        /// 机器人餐饮店
        /// </summary>
        RobotDining = 10,
        /// <summary>
        /// 艺术餐厅
        /// </summary>
        ArtRestaurant = 11,
        /// <summary>
        /// 沙滩烧烤店
        /// </summary>
        BeachBBQShack = 12,
        /// <summary>
        /// 熔岩食品店
        /// </summary>
        LavaCuisineDiner = 13,
        /// <summary>
        /// 植物猎人餐厅
        /// </summary>
        PlantHunterRestaurant = 14,
        /// <summary>
        /// 南国小酒馆
        /// </summary>
        SouthernTavern = 15,
        /// <summary>
        /// 秘境农产品店
        /// </summary>
        FarmShop = 16,
        /// <summary>
        /// 马场
        /// </summary>
        HorseRanch = 17,
        /// <summary>
        /// 集市食品店
        /// </summary>
        MarketFoodShop = 18,
        /// <summary>
        /// 果园
        /// </summary>
        Orchard = 19,
        /// <summary>
        /// 冰激凌店
        /// </summary>
        IceCreamShop = 20,
        /// <summary>
        /// 北欧餐厅
        /// </summary>
        NordicRestaurant = 21,
        /// <summary>
        /// 北海冰鱼堂
        /// </summary>
        FishHall = 22,
        /// <summary>
        /// 电厂
        /// </summary>
        PowerPlant = 23,
        /// <summary>
        /// 极光甜点坊
        /// </summary>
        AuroraDessertShop = 24,
        /// <summary>
        /// 寒霜寿司屋
        /// </summary>
        SushiShop = 25,
        /// <summary>
        /// 雪原野味馆
        /// </summary>
        WildHillRestaurant = 26,
        /// <summary>
        /// 中华火锅
        /// </summary>
        ChineseHotPot = 27,
    }

} 

