
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
/// <summary>
/// 建筑类型的具体信息
/// </summary>
public sealed partial class BuildingInfo : Luban.BeanBase
{
    public BuildingInfo(JSONNode _buf) 
    {
        { if(!_buf["isBuilding"].IsBoolean) { throw new SerializationException(); }  isBuilding = _buf["isBuilding"]; }
        { if(!_buf["buildingName"].IsString) { throw new SerializationException(); }  buildingName = _buf["buildingName"]; }
        { if(!_buf["buildingType"].IsNumber) { throw new SerializationException(); }  buildingType = (level.BuildingType)_buf["buildingType"].AsInt; }
        { if(!_buf["buildingLoc"].IsObject) { throw new SerializationException(); }  buildingLoc = global.LocalizedString.DeserializeLocalizedString(_buf["buildingLoc"]);  }
    }

    public static BuildingInfo DeserializeBuildingInfo(JSONNode _buf)
    {
        return new level.BuildingInfo(_buf);
    }

    public readonly bool isBuilding;
    public readonly string buildingName;
    public readonly level.BuildingType buildingType;
    public readonly global.LocalizedString buildingLoc;
   
    public const int __ID__ = 565259212;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        buildingLoc?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "isBuilding:" + isBuilding + ","
        + "buildingName:" + buildingName + ","
        + "buildingType:" + buildingType + ","
        + "buildingLoc:" + buildingLoc + ","
        + "}";
    }
}

}

