
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
/// <summary>
/// 商品具体信息
/// </summary>
public sealed partial class GoodsInfo : Luban.BeanBase
{
    public GoodsInfo(JSONNode _buf) 
    {
        { if(!_buf["goodsName"].IsString) { throw new SerializationException(); }  goodsName = _buf["goodsName"]; }
        { if(!_buf["goodsType"].IsNumber) { throw new SerializationException(); }  goodsType = (level.GoodsType)_buf["goodsType"].AsInt; }
        { if(!_buf["refreshCount"].IsNumber) { throw new SerializationException(); }  refreshCount = _buf["refreshCount"]; }
    }

    public static GoodsInfo DeserializeGoodsInfo(JSONNode _buf)
    {
        return new level.GoodsInfo(_buf);
    }

    public readonly string goodsName;
    public readonly level.GoodsType goodsType;
    /// <summary>
    /// 数字越大刷新概率越高，反之越低
    /// </summary>
    public readonly int refreshCount;
   
    public const int __ID__ = 2126991130;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "goodsName:" + goodsName + ","
        + "goodsType:" + goodsType + ","
        + "refreshCount:" + refreshCount + ","
        + "}";
    }
}

}

