
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class GoodsPoolTemplate : Luban.BeanBase
{
    public GoodsPoolTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["pool_name"].IsString) { throw new SerializationException(); }  poolName = _buf["pool_name"]; }
        { if(!_buf["pool_type"].IsNumber) { throw new SerializationException(); }  poolType = (level.PoolType)_buf["pool_type"].AsInt; }
        { var __json0 = _buf["goods_list"]; if(!__json0.IsArray) { throw new SerializationException(); } goodsList = new System.Collections.Generic.List<level.GoodsInfo>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { level.GoodsInfo __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = level.GoodsInfo.DeserializeGoodsInfo(__e0);  }  goodsList.Add(__v0); }   }
    }

    public static GoodsPoolTemplate DeserializeGoodsPoolTemplate(JSONNode _buf)
    {
        return new level.GoodsPoolTemplate(_buf);
    }

    public readonly int id;
    public readonly string poolName;
    public readonly level.PoolType poolType;
    public readonly System.Collections.Generic.List<level.GoodsInfo> goodsList;
   
    public const int __ID__ = 1318628130;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in goodsList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "poolName:" + poolName + ","
        + "poolType:" + poolType + ","
        + "goodsList:" + Luban.StringUtil.CollectionToString(goodsList) + ","
        + "}";
    }
}

}

