
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level
{ 
    /// <summary>
    /// 商品类型
    /// </summary>
    public enum GoodsType
    {
        /// <summary>
        /// 货箱
        /// </summary>
        Backpack = 0,
        /// <summary>
        /// 单元类道具
        /// </summary>
        Prop = 1,
        /// <summary>
        /// Buff类道具
        /// </summary>
        Buff = 2,
    }

} 

