
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level
{ 
    /// <summary>
    /// 读法：x行y列
    /// </summary>
    public enum GridShape
    {
        /// <summary>
        /// 00
        /// </summary>
        RECT_SQUARE_1x1 = 0,
        /// <summary>
        /// 00 01 10 11
        /// </summary>
        RECT_SQUARE_2x2 = 1,
        /// <summary>
        /// 00 01 02 10 11 12 20 21 22
        /// </summary>
        RECT_SQUARE_3x3 = 2,
        /// <summary>
        /// 00 10 11 21
        /// </summary>
        Z_SHAPE = 3,
        /// <summary>
        /// 01 10 11 20
        /// </summary>
        Z_SHAPE_MIRRORED = 4,
        /// <summary>
        /// 00 02 11 20 22
        /// </summary>
        X_SHAPE = 5,
        /// <summary>
        /// 01 10 11 12 21
        /// </summary>
        CROSS_SHAPE = 6,
        /// <summary>
        /// 00 01 11 21
        /// </summary>
        L_SHAPE_VERTICAL_FLAT = 7,
        /// <summary>
        /// 00 10 01 02
        /// </summary>
        L_SHAPE_HORIZONTAL_FLAT = 8,
        /// <summary>
        /// 00 10 20 21
        /// </summary>
        L_SHAPE_VERTICAL = 9,
        /// <summary>
        /// 00 01 02 10
        /// </summary>
        L_SHAPE_HORIZONTAL = 10,
        /// <summary>
        /// 00 01 11
        /// </summary>
        L_SHAPE_VERTICAL_SHORT = 11,
        /// <summary>
        /// 00 01 11 20 21
        /// </summary>
        U_SHAPE_SMALL = 12,
        /// <summary>
        /// 00 01 02 11 12 20 21 22
        /// </summary>
        U_SHAPE_BIG = 13,
        /// <summary>
        /// 10 01 11 21 02 22
        /// </summary>
        C_SHAPE = 14,
        /// <summary>
        /// 00 10
        /// </summary>
        RECT_HORIZONTAL_1x2 = 15,
        /// <summary>
        /// 00 10 20
        /// </summary>
        RECT_HORIZONTAL_1x3 = 16,
        /// <summary>
        /// 00 10 20 30
        /// </summary>
        RECT_HORIZONTAL_1x4 = 17,
        /// <summary>
        /// 00 10 20 10 11 21
        /// </summary>
        RECT_HORIZONTAL_2x3 = 18,
        /// <summary>
        /// 00 10 20 30 10 11 21 31
        /// </summary>
        RECT_HORIZONTAL_2x4 = 19,
        /// <summary>
        /// 00 01
        /// </summary>
        RECT_VERTICAL_2x1 = 20,
        /// <summary>
        /// 00 01 02
        /// </summary>
        RECT_VERTICAL_3x1 = 21,
        /// <summary>
        /// 00 01 02 03
        /// </summary>
        RECT_VERTICAL_4x1 = 22,
        /// <summary>
        /// 00 10 01 11 02 12
        /// </summary>
        RECT_VERTICAL_3x2 = 23,
        /// <summary>
        /// 00 10 20 11 12
        /// </summary>
        T_SHAPE = 24,
        /// <summary>
        /// 02 12 22 11 10
        /// </summary>
        T_SHAPE_REVERSED = 25,
        /// <summary>
        /// 00 10 11 20
        /// </summary>
        T_SHAPE_SHORT = 26,
        /// <summary>
        /// 00 10 20 12
        /// </summary>
        L_SHAPE_VERTICAL_REVERSED = 27
    }

} 

