
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class ItemTemplate : Luban.BeanBase
{
    public ItemTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["item_name"].IsString) { throw new SerializationException(); }  itemName = _buf["item_name"]; }
        { if(!_buf["item_source"].IsNumber) { throw new SerializationException(); }  itemSource = (level.BuildingType)_buf["item_source"].AsInt; }
        { if(!_buf["item_tags"].IsNumber) { throw new SerializationException(); }  itemTags = (level.ItemTag)_buf["item_tags"].AsInt; }
        { if(!_buf["shape"].IsNumber) { throw new SerializationException(); }  shape = (level.GridShape)_buf["shape"].AsInt; }
        { if(!_buf["item_size"].IsNumber) { throw new SerializationException(); }  itemSize = _buf["item_size"]; }
        { if(!_buf["item_value"].IsNumber) { throw new SerializationException(); }  itemValue = _buf["item_value"]; }
        { if(!_buf["item_localization"].IsObject) { throw new SerializationException(); }  itemLocalization = global.LocalizedString.DeserializeLocalizedString(_buf["item_localization"]);  }
    }

    public static ItemTemplate DeserializeItemTemplate(JSONNode _buf)
    {
        return new level.ItemTemplate(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 货物名称
    /// </summary>
    public readonly string itemName;
    /// <summary>
    /// 货物来源建筑（默认唯一）
    /// </summary>
    public readonly level.BuildingType itemSource;
    /// <summary>
    /// 货物词条（默认唯一）
    /// </summary>
    public readonly level.ItemTag itemTags;
    /// <summary>
    /// 货物形状
    /// </summary>
    public readonly level.GridShape shape;
    /// <summary>
    /// 货物尺寸
    /// </summary>
    public readonly int itemSize;
    /// <summary>
    /// 货物价值（奖励值）
    /// </summary>
    public readonly int itemValue;
    /// <summary>
    /// 本地化名称索引
    /// </summary>
    public readonly global.LocalizedString itemLocalization;
   
    public const int __ID__ = 854893303;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        itemLocalization?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "itemName:" + itemName + ","
        + "itemSource:" + itemSource + ","
        + "itemTags:" + itemTags + ","
        + "shape:" + shape + ","
        + "itemSize:" + itemSize + ","
        + "itemValue:" + itemValue + ","
        + "itemLocalization:" + itemLocalization + ","
        + "}";
    }
}

}

