
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Unity.VisualScripting;

namespace cfg.level
{ 
    [System.Flags]
    public enum ItemTag
    {
        /// <summary>
        /// 占位用Tag，临时代指货箱等非Tag相关物品。
        /// </summary>
        None = 0,
        /// <summary>
        /// 普通物品
        /// </summary>
        Ordinary = 1,
        /// <summary>
        /// 1级冷冻
        /// </summary>
        CoolI = 2,
        /// <summary>
        /// 2级冷冻
        /// </summary>
        CoolII = 3,
        /// <summary>
        /// 3级冷冻
        /// </summary>
        CoolIII = 4,
        /// <summary>
        /// 1级保鲜
        /// </summary>
        NaturalI = 5,
        /// <summary>
        /// 2级保鲜
        /// </summary>
        NaturalII = 6,
        /// <summary>
        /// 3级保鲜
        /// </summary>
        NaturalIII = 7,
        /// <summary>
        /// 1级减震
        /// </summary>
        FragileI = 8,
        /// <summary>
        /// 2级减震
        /// </summary>
        FragileII = 9,
        /// <summary>
        /// 3级减震
        /// </summary>
        FragileIII = 10,
        /// <summary>
        /// 1级保温
        /// </summary>
        HeatI = 11,
        /// <summary>
        /// 2级保温
        /// </summary>
        HeatII = 12,
        /// <summary>
        /// 3级保温
        /// </summary>
        HeatIII = 13,
        /// <summary>
        /// 必须放在角落
        /// </summary>
        NeedCorner = 14,
        /// <summary>
        /// 必须和某个物品放在一起
        /// </summary>
        LikeSomeone = 15,
        /// <summary>
        /// 不能和某个物品放在一起
        /// </summary>
        HateSomeone = 16,
    }

} 

