
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
/// <summary>
/// 关卡每回合任务信息
/// </summary>
public sealed partial class LevelTask : Luban.BeanBase
{
    public LevelTask(JSONNode _buf) 
    {
        { if(!_buf["roundName"].IsString) { throw new SerializationException(); }  roundName = _buf["roundName"]; }
        { if(!_buf["roundCount"].IsNumber) { throw new SerializationException(); }  roundCount = (level.LevelRound)_buf["roundCount"].AsInt; }
        { if(!_buf["roundTarget"].IsNumber) { throw new SerializationException(); }  roundTarget = _buf["roundTarget"]; }
        { var __json0 = _buf["taskPerRound"]; if(!__json0.IsArray) { throw new SerializationException(); } taskPerRound = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  taskPerRound.Add(_k0, _v0); }   }
    }

    public static LevelTask DeserializeLevelTask(JSONNode _buf)
    {
        return new level.LevelTask(_buf);
    }

    /// <summary>
    /// 仅用于标识
    /// </summary>
    public readonly string roundName;
    public readonly level.LevelRound roundCount;
    public readonly int roundTarget;
    public readonly System.Collections.Generic.Dictionary<string, int> taskPerRound;
   
    public const int __ID__ = -923509473;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "roundName:" + roundName + ","
        + "roundCount:" + roundCount + ","
        + "roundTarget:" + roundTarget + ","
        + "taskPerRound:" + Luban.StringUtil.CollectionToString(taskPerRound) + ","
        + "}";
    }
}

}

