
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class LevelTemplate : Luban.BeanBase
{
    public LevelTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["level_name"].IsString) { throw new SerializationException(); }  levelName = _buf["level_name"]; }
        { if(!_buf["flat_board_name"].IsString) { throw new SerializationException(); }  flatBoardName = _buf["flat_board_name"]; }
        { if(!_buf["vertical_board_name"].IsString) { throw new SerializationException(); }  verticalBoardName = _buf["vertical_board_name"]; }
        { var __json0 = _buf["level_tags"]; if(!__json0.IsArray) { throw new SerializationException(); } levelTags = new System.Collections.Generic.List<world.LevelTag>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { world.LevelTag __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (world.LevelTag)__e0.AsInt; }  levelTags.Add(__v0); }   }
        { if(!_buf["original_fuels"].IsNumber) { throw new SerializationException(); }  originalFuels = _buf["original_fuels"]; }
        { if(!_buf["original_coins"].IsNumber) { throw new SerializationException(); }  originalCoins = _buf["original_coins"]; }
        { if(!_buf["original_rounds"].IsNumber) { throw new SerializationException(); }  originalRounds = _buf["original_rounds"]; }
        { var __json0 = _buf["key_rounds"]; if(!__json0.IsArray) { throw new SerializationException(); } keyRounds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  keyRounds.Add(__v0); }   }
        { if(!_buf["start_pos"].IsObject) { throw new SerializationException(); }  startPos = ExternalTypeUtil.NewVector2Int(vector2int.Deserializevector2int(_buf["start_pos"]));  }
        { var __json0 = _buf["store_pools"]; if(!__json0.IsArray) { throw new SerializationException(); } storePools = new System.Collections.Generic.Dictionary<level.PoolType, string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { level.PoolType _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (level.PoolType)__e0[0].AsInt; } string _v0;  { if(!__e0[1].IsString) { throw new SerializationException(); }  _v0 = __e0[1]; }  storePools.Add(_k0, _v0); }   }
        { var __json0 = _buf["store_probability"]; if(!__json0.IsArray) { throw new SerializationException(); } storeProbability = new System.Collections.Generic.List<System.Collections.Generic.Dictionary<level.PoolType, float>>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { System.Collections.Generic.Dictionary<level.PoolType, float> __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } __v0 = new System.Collections.Generic.Dictionary<level.PoolType, float>(__json1.Count); foreach(JSONNode __e1 in __json1.Children) { level.PoolType _k1;  { if(!__e1[0].IsNumber) { throw new SerializationException(); }  _k1 = (level.PoolType)__e1[0].AsInt; } float _v1;  { if(!__e1[1].IsNumber) { throw new SerializationException(); }  _v1 = __e1[1]; }  __v0.Add(_k1, _v1); }   }  storeProbability.Add(__v0); }   }
        { var __json0 = _buf["task_list"]; if(!__json0.IsArray) { throw new SerializationException(); } taskList = new System.Collections.Generic.List<level.LevelTask>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { level.LevelTask __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = level.LevelTask.DeserializeLevelTask(__e0);  }  taskList.Add(__v0); }   }
    }

    public static LevelTemplate DeserializeLevelTemplate(JSONNode _buf)
    {
        return new level.LevelTemplate(_buf);
    }

    public readonly int id;
    public readonly string levelName;
    public readonly string flatBoardName;
    public readonly string verticalBoardName;
    public readonly System.Collections.Generic.List<world.LevelTag> levelTags;
    public readonly int originalFuels;
    public readonly int originalCoins;
    public readonly int originalRounds;
    public readonly System.Collections.Generic.List<int> keyRounds;
    public readonly UnityEngine.Vector2Int startPos;
    public readonly System.Collections.Generic.Dictionary<level.PoolType, string> storePools;
    public readonly System.Collections.Generic.List<System.Collections.Generic.Dictionary<level.PoolType, float>> storeProbability;
    public readonly System.Collections.Generic.List<level.LevelTask> taskList;
   
    public const int __ID__ = 419927828;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in taskList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "levelName:" + levelName + ","
        + "flatBoardName:" + flatBoardName + ","
        + "verticalBoardName:" + verticalBoardName + ","
        + "levelTags:" + Luban.StringUtil.CollectionToString(levelTags) + ","
        + "originalFuels:" + originalFuels + ","
        + "originalCoins:" + originalCoins + ","
        + "originalRounds:" + originalRounds + ","
        + "keyRounds:" + Luban.StringUtil.CollectionToString(keyRounds) + ","
        + "startPos:" + startPos + ","
        + "storePools:" + Luban.StringUtil.CollectionToString(storePools) + ","
        + "storeProbability:" + Luban.StringUtil.CollectionToString(storeProbability) + ","
        + "taskList:" + Luban.StringUtil.CollectionToString(taskList) + ","
        + "}";
    }
}

}

