
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level
{ 
    /// <summary>
    /// 回合数
    /// </summary>
    public enum LevelRound
    {
        /// <summary>
        /// 第1回合
        /// </summary>
        ROUND_1 = 1,
        /// <summary>
        /// 第2回合
        /// </summary>
        ROUND_2 = 2,
        /// <summary>
        /// 第3回合
        /// </summary>
        ROUND_3 = 3,
        /// <summary>
        /// 第4回合
        /// </summary>
        ROUND_4 = 4,
        /// <summary>
        /// 第5回合
        /// </summary>
        ROUND_5 = 5,
        /// <summary>
        /// 第6回合
        /// </summary>
        ROUND_6 = 6,
        /// <summary>
        /// 第7回合
        /// </summary>
        ROUND_7 = 7,
        /// <summary>
        /// 第8回合
        /// </summary>
        ROUND_8 = 8,
        /// <summary>
        /// 第9回合
        /// </summary>
        ROUND_9 = 9,
        /// <summary>
        /// 第10回合
        /// </summary>
        ROUND_10 = 10,
        /// <summary>
        /// 第11回合
        /// </summary>
        ROUND_11 = 11,
        /// <summary>
        /// 第12回合
        /// </summary>
        ROUND_12 = 12,
        /// <summary>
        /// 第13回合
        /// </summary>
        ROUND_13 = 13,
        /// <summary>
        /// 第14回合
        /// </summary>
        ROUND_14 = 14,
        /// <summary>
        /// 第15回合
        /// </summary>
        ROUND_15 = 15,
        /// <summary>
        /// 第16回合
        /// </summary>
        ROUND_16 = 16,
        /// <summary>
        /// 第17回合
        /// </summary>
        ROUND_17 = 17,
        /// <summary>
        /// 第18回合
        /// </summary>
        ROUND_18 = 18,
        /// <summary>
        /// 第19回合
        /// </summary>
        ROUND_19 = 19,
        /// <summary>
        /// 第20回合
        /// </summary>
        ROUND_20 = 20,
    }

} 

