
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class PropTemplate : Luban.BeanBase
{
    public PropTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["prop_name"].IsString) { throw new SerializationException(); }  propName = _buf["prop_name"]; }
        { if(!_buf["shape"].IsNumber) { throw new SerializationException(); }  shape = (level.GridShape)_buf["shape"].AsInt; }
        { if(!_buf["prop_size"].IsNumber) { throw new SerializationException(); }  propSize = _buf["prop_size"]; }
        { if(!_buf["prop_value"].IsNumber) { throw new SerializationException(); }  propValue = _buf["prop_value"]; }
        { if(!_buf["prop_price"].IsNumber) { throw new SerializationException(); }  propPrice = _buf["prop_price"]; }
        { if(!_buf["prop_localization"].IsObject) { throw new SerializationException(); }  propLocalization = global.LocalizedString.DeserializeLocalizedString(_buf["prop_localization"]);  }
    }

    public static PropTemplate DeserializePropTemplate(JSONNode _buf)
    {
        return new level.PropTemplate(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 单元名称
    /// </summary>
    public readonly string propName;
    /// <summary>
    /// 单元形状
    /// </summary>
    public readonly level.GridShape shape;
    /// <summary>
    /// 单元尺寸
    /// </summary>
    public readonly int propSize;
    /// <summary>
    /// 单元价值（卖出）
    /// </summary>
    public readonly int propValue;
    /// <summary>
    /// 单元售价（买入）
    /// </summary>
    public readonly int propPrice;
    /// <summary>
    /// 本地化名称索引
    /// </summary>
    public readonly global.LocalizedString propLocalization;
   
    public const int __ID__ = -2035123385;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        propLocalization?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "propName:" + propName + ","
        + "shape:" + shape + ","
        + "propSize:" + propSize + ","
        + "propValue:" + propValue + ","
        + "propPrice:" + propPrice + ","
        + "propLocalization:" + propLocalization + ","
        + "}";
    }
}

}

