
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public sealed partial class TaskTemplate : Luban.BeanBase
{
    public TaskTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["template_name"].IsString) { throw new SerializationException(); }  templateName = _buf["template_name"]; }
        { if(!_buf["building_name"].IsString) { throw new SerializationException(); }  buildingName = _buf["building_name"]; }
        { if(!_buf["building_type"].IsNumber) { throw new SerializationException(); }  buildingType = (level.BuildingType)_buf["building_type"].AsInt; }
        { if(!_buf["task_reward"].IsNumber) { throw new SerializationException(); }  taskReward = _buf["task_reward"]; }
        { if(!_buf["max_item_value"].IsNumber) { throw new SerializationException(); }  maxItemValue = _buf["max_item_value"]; }
        { if(!_buf["min_item_value"].IsNumber) { throw new SerializationException(); }  minItemValue = _buf["min_item_value"]; }
        { if(!_buf["max_item_count"].IsNumber) { throw new SerializationException(); }  maxItemCount = _buf["max_item_count"]; }
        { if(!_buf["min_item_count"].IsNumber) { throw new SerializationException(); }  minItemCount = _buf["min_item_count"]; }
    }

    public static TaskTemplate DeserializeTaskTemplate(JSONNode _buf)
    {
        return new level.TaskTemplate(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 任务模版名称
    /// </summary>
    public readonly string templateName;
    /// <summary>
    /// 任务建筑名称（用于查找位置）
    /// </summary>
    public readonly string buildingName;
    /// <summary>
    /// 任务建筑类型（用于查找图标）
    /// </summary>
    public readonly level.BuildingType buildingType;
    /// <summary>
    /// 任务完成奖励
    /// </summary>
    public readonly int taskReward;
    /// <summary>
    /// 刷新货物总计最大价值
    /// </summary>
    public readonly int maxItemValue;
    /// <summary>
    /// 刷新货物总计最小价值
    /// </summary>
    public readonly int minItemValue;
    /// <summary>
    /// 刷新货物总计最大数量
    /// </summary>
    public readonly int maxItemCount;
    /// <summary>
    /// 刷新货物总计最小数量
    /// </summary>
    public readonly int minItemCount;
   
    public const int __ID__ = -1374106775;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "templateName:" + templateName + ","
        + "buildingName:" + buildingName + ","
        + "buildingType:" + buildingType + ","
        + "taskReward:" + taskReward + ","
        + "maxItemValue:" + maxItemValue + ","
        + "minItemValue:" + minItemValue + ","
        + "maxItemCount:" + maxItemCount + ","
        + "minItemCount:" + minItemCount + ","
        + "}";
    }
}

}

