
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public partial class TbGoodsPoolTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, level.GoodsPoolTemplate> _dataMap;
    private readonly System.Collections.Generic.List<level.GoodsPoolTemplate> _dataList;
    
    public TbGoodsPoolTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.GoodsPoolTemplate>();
        _dataList = new System.Collections.Generic.List<level.GoodsPoolTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            level.GoodsPoolTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = level.GoodsPoolTemplate.DeserializeGoodsPoolTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.GoodsPoolTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<level.GoodsPoolTemplate> DataList => _dataList;

    public level.GoodsPoolTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.GoodsPoolTemplate Get(int key) => _dataMap[key];
    public level.GoodsPoolTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

