
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public partial class TbItemTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, level.ItemTemplate> _dataMap;
    private readonly System.Collections.Generic.List<level.ItemTemplate> _dataList;
    
    public TbItemTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.ItemTemplate>();
        _dataList = new System.Collections.Generic.List<level.ItemTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            level.ItemTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = level.ItemTemplate.DeserializeItemTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.ItemTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<level.ItemTemplate> DataList => _dataList;

    public level.ItemTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.ItemTemplate Get(int key) => _dataMap[key];
    public level.ItemTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

