
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public partial class TbLevelTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, level.LevelTemplate> _dataMap;
    private readonly System.Collections.Generic.List<level.LevelTemplate> _dataList;
    
    public TbLevelTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.LevelTemplate>();
        _dataList = new System.Collections.Generic.List<level.LevelTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            level.LevelTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = level.LevelTemplate.DeserializeLevelTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.LevelTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<level.LevelTemplate> DataList => _dataList;

    public level.LevelTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.LevelTemplate Get(int key) => _dataMap[key];
    public level.LevelTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

