
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level
{
public partial class TbPropTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, level.PropTemplate> _dataMap;
    private readonly System.Collections.Generic.List<level.PropTemplate> _dataList;
    
    public TbPropTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.PropTemplate>();
        _dataList = new System.Collections.Generic.List<level.PropTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            level.PropTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = level.PropTemplate.DeserializePropTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.PropTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<level.PropTemplate> DataList => _dataList;

    public level.PropTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.PropTemplate Get(int key) => _dataMap[key];
    public level.PropTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

