
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.global
{
/// <summary>
/// I2插件专用
/// </summary>
public sealed partial class LocalizedString : Luban.BeanBase
{
    public LocalizedString(JSONNode _buf) 
    {
        { if(!_buf["localizedName"].IsString) { throw new SerializationException(); }  localizedName = _buf["localizedName"]; }
        { if(!_buf["localizedDes"].IsString) { throw new SerializationException(); }  localizedDes = _buf["localizedDes"]; }
    }

    public static LocalizedString DeserializeLocalizedString(JSONNode _buf)
    {
        return new global.LocalizedString(_buf);
    }

    /// <summary>
    /// 本地化名称文本索引
    /// </summary>
    public readonly string localizedName;
    /// <summary>
    /// 本地化描述文本索引
    /// </summary>
    public readonly string localizedDes;
   
    public const int __ID__ = 1315060481;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "localizedName:" + localizedName + ","
        + "localizedDes:" + localizedDes + ","
        + "}";
    }
}

}

