
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public level.map.TbTileTemplate TbTileTemplate {get; }
    public level.TbItemTemplate TbItemTemplate {get; }
    public level.TbPropTemplate TbPropTemplate {get; }
    public level.TbBackpackTemplate TbBackpackTemplate {get; }
    public level.TbLevelTemplate TbLevelTemplate {get; }
    public level.TbTaskTemplate TbTaskTemplate {get; }
    public level.TbGoodsPoolTemplate TbGoodsPoolTemplate {get; }
    public world.map.TbTownTemplate TbTownTemplate {get; }
    public world.map.TbDirectionRules TbDirectionRules {get; }
    public world.map.TbPlacementRules TbPlacementRules {get; }
    public world.map.TbPipeTemplate TbPipeTemplate {get; }
    public level.map.TbBoardTemplate TbBoardTemplate {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbTileTemplate = new level.map.TbTileTemplate(loader("level_map_tbtiletemplate"));
        TbItemTemplate = new level.TbItemTemplate(loader("level_tbitemtemplate"));
        TbPropTemplate = new level.TbPropTemplate(loader("level_tbproptemplate"));
        TbBackpackTemplate = new level.TbBackpackTemplate(loader("level_tbbackpacktemplate"));
        TbLevelTemplate = new level.TbLevelTemplate(loader("level_tbleveltemplate"));
        TbTaskTemplate = new level.TbTaskTemplate(loader("level_tbtasktemplate"));
        TbGoodsPoolTemplate = new level.TbGoodsPoolTemplate(loader("level_tbgoodspooltemplate"));
        TbTownTemplate = new world.map.TbTownTemplate(loader("world_map_tbtowntemplate"));
        TbDirectionRules = new world.map.TbDirectionRules(loader("world_map_tbdirectionrules"));
        TbPlacementRules = new world.map.TbPlacementRules(loader("world_map_tbplacementrules"));
        TbPipeTemplate = new world.map.TbPipeTemplate(loader("world_map_tbpipetemplate"));
        TbBoardTemplate = new level.map.TbBoardTemplate(loader("level_map_tbboardtemplate"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTileTemplate.ResolveRef(this);
        TbItemTemplate.ResolveRef(this);
        TbPropTemplate.ResolveRef(this);
        TbBackpackTemplate.ResolveRef(this);
        TbLevelTemplate.ResolveRef(this);
        TbTaskTemplate.ResolveRef(this);
        TbGoodsPoolTemplate.ResolveRef(this);
        TbTownTemplate.ResolveRef(this);
        TbDirectionRules.ResolveRef(this);
        TbPlacementRules.ResolveRef(this);
        TbPipeTemplate.ResolveRef(this);
        TbBoardTemplate.ResolveRef(this);
    }
}

}
