
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial struct vector2
{
    public vector2(JSONNode _buf) 
    {
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  x = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  y = _buf["y"]; }
    }

    public static vector2 Deserializevector2(JSONNode _buf)
    {
        return new vector2(_buf);
    }

    public readonly float x;
    public readonly float y;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + x + ","
        + "y:" + y + ","
        + "}";
    }
}

}

