
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level.map
{
/// <summary>
/// 棋盘每一列的数据
/// </summary>
public sealed partial class BoardColumn : Luban.BeanBase
{
    public BoardColumn(JSONNode _buf) 
    {
        { var __json0 = _buf["column"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; column = new level.map.BoardCell[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { level.map.BoardCell __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = level.map.BoardCell.DeserializeBoardCell(__e0);  }  column[__index0++] = __v0; }   }
    }

    public static BoardColumn DeserializeBoardColumn(JSONNode _buf)
    {
        return new level.map.BoardColumn(_buf);
    }

    public readonly level.map.BoardCell[] column;
   
    public const int __ID__ = 295777728;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in column) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "column:" + Luban.StringUtil.CollectionToString(column) + ","
        + "}";
    }
}

}

