
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level.map
{
/// <summary>
/// 棋盘每一格的具体数据
/// </summary>
public sealed partial class BoardCell : Luban.BeanBase
{
    public BoardCell(JSONNode _buf) 
    {
        { if(!_buf["upperLayer"].IsString) { throw new SerializationException(); }  upperLayer = _buf["upperLayer"]; }
        { if(!_buf["baseLayer"].IsString) { throw new SerializationException(); }  baseLayer = _buf["baseLayer"]; }
    }

    public static BoardCell DeserializeBoardCell(JSONNode _buf)
    {
        return new level.map.BoardCell(_buf);
    }

    public readonly string upperLayer;
    public readonly string baseLayer;
   
    public const int __ID__ = -1782940084;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "upperLayer:" + upperLayer + ","
        + "baseLayer:" + baseLayer + ","
        + "}";
    }
}

}

