
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level.map
{
public sealed partial class BoardTemplate : Luban.BeanBase
{
    public BoardTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["board_name"].IsString) { throw new SerializationException(); }  boardName = _buf["board_name"]; }
        { if(!_buf["board_width"].IsNumber) { throw new SerializationException(); }  boardWidth = _buf["board_width"]; }
        { if(!_buf["board_height"].IsNumber) { throw new SerializationException(); }  boardHeight = _buf["board_height"]; }
        { if(!_buf["bright_tile_name"].IsString) { throw new SerializationException(); }  brightTileName = _buf["bright_tile_name"]; }
        { if(!_buf["dark_tile_name"].IsString) { throw new SerializationException(); }  darkTileName = _buf["dark_tile_name"]; }
        { if(!_buf["water_tile_name"].IsString) { throw new SerializationException(); }  waterTileName = _buf["water_tile_name"]; }
        { var __json0 = _buf["board_map"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; boardMap = new level.map.BoardColumn[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { level.map.BoardColumn __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = level.map.BoardColumn.DeserializeBoardColumn(__e0);  }  boardMap[__index0++] = __v0; }   }
    }

    public static BoardTemplate DeserializeBoardTemplate(JSONNode _buf)
    {
        return new level.map.BoardTemplate(_buf);
    }

    public readonly int id;
    public readonly string boardName;
    public readonly int boardWidth;
    public readonly int boardHeight;
    public readonly string brightTileName;
    public readonly string darkTileName;
    public readonly string waterTileName;
    public readonly level.map.BoardColumn[] boardMap;
   
    public const int __ID__ = 76430436;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in boardMap) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "boardName:" + boardName + ","
        + "boardWidth:" + boardWidth + ","
        + "boardHeight:" + boardHeight + ","
        + "brightTileName:" + brightTileName + ","
        + "darkTileName:" + darkTileName + ","
        + "waterTileName:" + waterTileName + ","
        + "boardMap:" + Luban.StringUtil.CollectionToString(boardMap) + ","
        + "}";
    }
}

}

