
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level.map
{ 
    /// <summary>
    /// 地图主题
    /// </summary>
    public enum BoardTheme
    {
        /// <summary>
        /// 通用
        /// </summary>
        Common = 0,
        /// <summary>
        /// 春
        /// </summary>
        Spring = 1,
        /// <summary>
        /// 夏
        /// </summary>
        Summer = 2,
        /// <summary>
        /// 秋
        /// </summary>
        Autunm = 3,
        /// <summary>
        /// 冬
        /// </summary>
        Winter = 4,
    }

} 

