
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level.map
{
public partial class TbBoardTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, level.map.BoardTemplate> _dataMap;
    private readonly System.Collections.Generic.List<level.map.BoardTemplate> _dataList;
    
    public TbBoardTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, level.map.BoardTemplate>();
        _dataList = new System.Collections.Generic.List<level.map.BoardTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            level.map.BoardTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = level.map.BoardTemplate.DeserializeBoardTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, level.map.BoardTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<level.map.BoardTemplate> DataList => _dataList;

    public level.map.BoardTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.map.BoardTemplate Get(int key) => _dataMap[key];
    public level.map.BoardTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

