
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.level.map
{ 
    /// <summary>
    /// 地块类型
    /// </summary>
    public enum TileType
    {
        /// <summary>
        /// 地形类型
        /// </summary>
        Terrain = 0,
        /// <summary>
        /// 结构类型
        /// </summary>
        Structure = 1,
        /// <summary>
        /// 1x1
        /// </summary>
        Vertical = 2,
        /// <summary>
        /// 1x0.78
        /// </summary>
        DeepFlat = 3,
    }

} 

