
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level.map
{
public sealed partial class TileTemplate : Luban.BeanBase
{
    public TileTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["tile_name"].IsString) { throw new SerializationException(); }  tileName = _buf["tile_name"]; }
        { if(!_buf["tile_type"].IsNumber) { throw new SerializationException(); }  tileType = (level.map.TileType)_buf["tile_type"].AsInt; }
        { if(!_buf["tile_theme"].IsNumber) { throw new SerializationException(); }  tileTheme = (level.map.BoardTheme)_buf["tile_theme"].AsInt; }
        { if(!_buf["tile_offsetY"].IsNumber) { throw new SerializationException(); }  tileOffsetY = _buf["tile_offsetY"]; }
        { if(!_buf["tile_addon"].IsObject) { throw new SerializationException(); }  tileAddon = level.BuildingInfo.DeserializeBuildingInfo(_buf["tile_addon"]);  }
    }

    public static TileTemplate DeserializeTileTemplate(JSONNode _buf)
    {
        return new level.map.TileTemplate(_buf);
    }

    public readonly int id;
    public readonly string tileName;
    public readonly level.map.TileType tileType;
    public readonly level.map.BoardTheme tileTheme;
    public readonly float tileOffsetY;
    /// <summary>
    /// 详细信息（是否为可交互建筑、可生成任务或者事件）
    /// </summary>
    public readonly level.BuildingInfo tileAddon;
   
    public const int __ID__ = -1398757916;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        tileAddon?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "tileName:" + tileName + ","
        + "tileType:" + tileType + ","
        + "tileTheme:" + tileTheme + ","
        + "tileOffsetY:" + tileOffsetY + ","
        + "tileAddon:" + tileAddon + ","
        + "}";
    }
}

}

