
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world.map
{
public sealed partial class DirectionRules : Luban.BeanBase
{
    public DirectionRules(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["target_offset"].IsObject) { throw new SerializationException(); }  targetOffset = ExternalTypeUtil.NewVector2Int(vector2int.Deserializevector2int(_buf["target_offset"]));  }
        { var __json0 = _buf["target_directions"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; targetDirections = new world.map.Direction[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { world.map.Direction __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (world.map.Direction)__e0.AsInt; }  targetDirections[__index0++] = __v0; }   }
    }

    public static DirectionRules DeserializeDirectionRules(JSONNode _buf)
    {
        return new world.map.DirectionRules(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 相对位置
    /// </summary>
    public readonly UnityEngine.Vector2Int targetOffset;
    /// <summary>
    /// 可连接方向1
    /// </summary>
    public readonly world.map.Direction[] targetDirections;
   
    public const int __ID__ = 14834566;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "targetOffset:" + targetOffset + ","
        + "targetDirections:" + Luban.StringUtil.CollectionToString(targetDirections) + ","
        + "}";
    }
}

}

