
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界方向表示
    /// </summary>
    public enum Direction
    {
        /// <summary>
        /// 上下左右
        /// </summary>
        Cross = 0,
        /// <summary>
        /// 上下
        /// </summary>
        Vertical = 1,
        /// <summary>
        /// 左右
        /// </summary>
        Horizontal = 2,
        /// <summary>
        /// 上右
        /// </summary>
        TopRight = 3,
        /// <summary>
        /// 上左
        /// </summary>
        TopLeft = 4,
        /// <summary>
        /// 下右
        /// </summary>
        BottomRight = 5,
        /// <summary>
        /// 下左
        /// </summary>
        BottomLeft = 6,
        /// <summary>
        /// 左右下
        /// </summary>
        LeftBottomRight = 7,
        /// <summary>
        /// 左右上
        /// </summary>
        LeftTopRight = 8,
        /// <summary>
        /// 上下左
        /// </summary>
        TopLeftBottom = 9,
        /// <summary>
        /// 上下右
        /// </summary>
        TopRightBottom = 10,
    }

} 

