
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界管道等级
    /// </summary>
    public enum PipeRank
    {
        /// <summary>
        /// 低
        /// </summary>
        Low = 0,
        /// <summary>
        /// 中
        /// </summary>
        Medium = 1,
        /// <summary>
        /// 高
        /// </summary>
        High = 2,
        /// <summary>
        /// 旗舰
        /// </summary>
        Ultra = 3,
    }

} 

