
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world.map
{
public sealed partial class PipeTemplate : Luban.BeanBase
{
    public PipeTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["pipe_name"].IsString) { throw new SerializationException(); }  pipeName = _buf["pipe_name"]; }
        { if(!_buf["pipe_rank"].IsNumber) { throw new SerializationException(); }  pipeRank = (world.map.PipeRank)_buf["pipe_rank"].AsInt; }
        { var __json0 = _buf["pipe_available_terrain"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; pipeAvailableTerrain = new world.map.TerrainType[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { world.map.TerrainType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (world.map.TerrainType)__e0.AsInt; }  pipeAvailableTerrain[__index0++] = __v0; }   }
        { if(!_buf["pipe_direction"].IsNumber) { throw new SerializationException(); }  pipeDirection = (world.map.Direction)_buf["pipe_direction"].AsInt; }
        { if(!_buf["pipe_weights"].IsNumber) { throw new SerializationException(); }  pipeWeights = _buf["pipe_weights"]; }
        { if(!_buf["pipe_localized_name"].IsString) { throw new SerializationException(); }  pipeLocalizedName = _buf["pipe_localized_name"]; }
    }

    public static PipeTemplate DeserializePipeTemplate(JSONNode _buf)
    {
        return new world.map.PipeTemplate(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 管道名称
    /// </summary>
    public readonly string pipeName;
    /// <summary>
    /// 管道等级
    /// </summary>
    public readonly world.map.PipeRank pipeRank;
    /// <summary>
    /// 管道可用范围
    /// </summary>
    public readonly world.map.TerrainType[] pipeAvailableTerrain;
    /// <summary>
    /// 管道方向
    /// </summary>
    public readonly world.map.Direction pipeDirection;
    /// <summary>
    /// 管道随机权重值
    /// </summary>
    public readonly int pipeWeights;
    /// <summary>
    /// 本地化名称索引
    /// </summary>
    public readonly string pipeLocalizedName;
   
    public const int __ID__ = -2125811050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "pipeName:" + pipeName + ","
        + "pipeRank:" + pipeRank + ","
        + "pipeAvailableTerrain:" + Luban.StringUtil.CollectionToString(pipeAvailableTerrain) + ","
        + "pipeDirection:" + pipeDirection + ","
        + "pipeWeights:" + pipeWeights + ","
        + "pipeLocalizedName:" + pipeLocalizedName + ","
        + "}";
    }
}

}

