
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world.map
{
public sealed partial class PlacementRules : Luban.BeanBase
{
    public PlacementRules(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["main_direction"].IsNumber) { throw new SerializationException(); }  mainDirection = (world.map.Direction)_buf["main_direction"].AsInt; }
        { var __json0 = _buf["available_offset"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; availableOffset = new UnityEngine.Vector2Int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { UnityEngine.Vector2Int __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ExternalTypeUtil.NewVector2Int(vector2int.Deserializevector2int(__e0));  }  availableOffset[__index0++] = __v0; }   }
    }

    public static PlacementRules DeserializePlacementRules(JSONNode _buf)
    {
        return new world.map.PlacementRules(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 基准方向
    /// </summary>
    public readonly world.map.Direction mainDirection;
    /// <summary>
    /// 相对位置1
    /// </summary>
    public readonly UnityEngine.Vector2Int[] availableOffset;
   
    public const int __ID__ = -960397344;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "mainDirection:" + mainDirection + ","
        + "availableOffset:" + Luban.StringUtil.CollectionToString(availableOffset) + ","
        + "}";
    }
}

}

