
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界季节类型
    /// </summary>
    public enum Season
    {
        /// <summary>
        /// 春
        /// </summary>
        Spring = 0,
        /// <summary>
        /// 夏
        /// </summary>
        Summer = 1,
        /// <summary>
        /// 秋
        /// </summary>
        Autumn = 2,
        /// <summary>
        /// 冬
        /// </summary>
        Winter = 3,
    }

} 

