
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界单格结构类型
    /// </summary>
    public enum StructureType
    {
        Empty = 0,
        Town = 1,
        Pipe = 2,
    }

} 

