
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world.map
{
public partial class TbPipeTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, world.map.PipeTemplate> _dataMap;
    private readonly System.Collections.Generic.List<world.map.PipeTemplate> _dataList;
    
    public TbPipeTemplate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, world.map.PipeTemplate>();
        _dataList = new System.Collections.Generic.List<world.map.PipeTemplate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            world.map.PipeTemplate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = world.map.PipeTemplate.DeserializePipeTemplate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, world.map.PipeTemplate> DataMap => _dataMap;
    public System.Collections.Generic.List<world.map.PipeTemplate> DataList => _dataList;

    public world.map.PipeTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public world.map.PipeTemplate Get(int key) => _dataMap[key];
    public world.map.PipeTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

