
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界单格地形类型
    /// </summary>
    public enum TerrainType
    {
        /// <summary>
        /// 普通地面
        /// </summary>
        Grassland = 0,
        /// <summary>
        /// 林地
        /// </summary>
        Forest = 1,
        /// <summary>
        /// 海洋
        /// </summary>
        Ocean = 2,
        /// <summary>
        /// 山地
        /// </summary>
        Mountain = 3,
        /// <summary>
        /// 禁区
        /// </summary>
        Locked = 4,
    }

} 

