
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.world.map
{ 
    /// <summary>
    /// 大世界城镇类型
    /// </summary>
    public enum TownType
    {
        /// <summary>
        /// BUFF收益类城镇
        /// </summary>
        Support = 0,
        /// <summary>
        /// 资金收益类城镇
        /// </summary>
        Economic = 1,
    }

} 

