
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.world.map
{
public sealed partial class TownTemplate : Luban.BeanBase
{
    public TownTemplate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["town_name"].IsString) { throw new SerializationException(); }  townName = _buf["town_name"]; }
        { if(!_buf["town_season"].IsNumber) { throw new SerializationException(); }  townSeason = (world.map.Season)_buf["town_season"].AsInt; }
        { if(!_buf["town_type"].IsNumber) { throw new SerializationException(); }  townType = (world.map.TownType)_buf["town_type"].AsInt; }
        { if(!_buf["town_direction"].IsNumber) { throw new SerializationException(); }  townDirection = (world.map.Direction)_buf["town_direction"].AsInt; }
        { if(!_buf["town_position"].IsObject) { throw new SerializationException(); }  townPosition = ExternalTypeUtil.NewVector2Int(vector2int.Deserializevector2int(_buf["town_position"]));  }
        { if(!_buf["town_level_name"].IsObject) { throw new SerializationException(); }  townLevelName = world.TownLevelDict.DeserializeTownLevelDict(_buf["town_level_name"]);  }
        { if(!_buf["town_localization"].IsObject) { throw new SerializationException(); }  townLocalization = global.LocalizedString.DeserializeLocalizedString(_buf["town_localization"]);  }
    }

    public static TownTemplate DeserializeTownTemplate(JSONNode _buf)
    {
        return new world.map.TownTemplate(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int id;
    /// <summary>
    /// 城镇名称
    /// </summary>
    public readonly string townName;
    /// <summary>
    /// 城镇所属季节
    /// </summary>
    public readonly world.map.Season townSeason;
    /// <summary>
    /// 城镇类型
    /// </summary>
    public readonly world.map.TownType townType;
    /// <summary>
    /// 城镇连通方向
    /// </summary>
    public readonly world.map.Direction townDirection;
    /// <summary>
    /// 城镇位置（仅参考）
    /// </summary>
    public readonly UnityEngine.Vector2Int townPosition;
    /// <summary>
    /// 简单难度关卡名
    /// </summary>
    public readonly world.TownLevelDict townLevelName;
    /// <summary>
    /// 本地化名称索引
    /// </summary>
    public readonly global.LocalizedString townLocalization;
   
    public const int __ID__ = 30898042;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        townLevelName?.ResolveRef(tables);
        townLocalization?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "townName:" + townName + ","
        + "townSeason:" + townSeason + ","
        + "townType:" + townType + ","
        + "townDirection:" + townDirection + ","
        + "townPosition:" + townPosition + ","
        + "townLevelName:" + townLevelName + ","
        + "townLocalization:" + townLocalization + ","
        + "}";
    }
}

}

